### PR TITLE
Enable dependabot to automatically get dependency updates

### PR DESCRIPTION
**Pull request by MRamonLeon**
It would be great to have **Dependabot** configured to get dependencies updates filed automatically. This will help avoiding bugs or security vulnerabilities from old dependencies.

Some helpful documentation about Dependabot to fine adjust it if needed:

* Keeping your dependencies updated automatically: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically
* Avoiding security vulnerabilities: https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/configuring-github-dependabot-security-updates
* Fine adjusting the configuration: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

### CODE REVIEW

**Comment by MRamonLeon** [comment]
cc: @batmat

**Comment by MRamonLeon** [comment]
Failure doesn't seem to be related:

``` 
 ERROR: Error cloning remote repo 'origin'
[2020-10-08T15:13:13.365Z] hudson.plugins.git.GitException: hudson.remoting.ProxyException: org.eclipse.jgit.errors.TranslationBundleLoadingException: Loading of translation bundle failed for [org.eclipse.jgit.internal.JGitText, en]
[2020-10-08T15:13:13.365Z] 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:148)
[2020-10-08T15:13:13.365Z] 	at jdk.internal.reflect.GeneratedMethodAccessor818.invoke(Unknown Source)
[2020-10-08T15:13:13.365Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-10-08T15:13:13.365Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2020-10-08T15:13:13.365Z] 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
[2020-10-08T15:13:13.365Z] 	at com.sun.proxy.$Proxy384.execute(Unknown Source)
[2020-10-08T15:13:13.365Z] 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1219)
[2020-10-08T15:13:13.365Z] 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1297)
[2020-10-08T15:13:13.365Z] 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
[2020-10-08T15:13:13.365Z] 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
[2020-10-08T15:13:13.365Z] 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
[2020-10-08T15:13:13.365Z] 	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
[2020-10-08T15:13:13.365Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2020-10-08T15:13:13.365Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2020-10-08T15:13:13.365Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2020-10-08T15:13:13.365Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2020-10-08T15:13:13.365Z] 	at java.base/java.lang.Thread.run(Thread.java:834)
[2020-10-08T15:13:13.365Z] Caused by: hudson.remoting.ProxyException: org.eclipse.jgit.errors.TranslationBundleLoadingException: Loading of translation bundle failed for [org.eclipse.jgit.internal.JGitText, en]

```

**Comment by batmat** [comment]
reopening/retriggering

**Review by batmat — APPROVED** [review]
Infra failure on Windows. As a maintainer, I'll merge this anyway.

**Pull request merged**
